### ISSUE TITLE
ValueError: could not convert string to float: 'so'

### ISSUE THREAD

**Issue by jorenham** [aalireza/SimpleAudioIndexer#10]
CMU mode works fine on the example .wav, but on my own 5-minute .wav with several tried keywords, I get the following stacktrace:

```bash
$ sai --mode "cmu" --src_dir data/sample --search "security"
Traceback (most recent call last):
  File "/project/venv/bin/sai", line 10, in <module>
    sys.exit(Main())
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__main__.py", line 101, in Main
    cli_script_wrapped(indexer)
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__main__.py", line 73, in cli_script_wrapped
    indexer.index_audio()
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 1110, in index_audio
    self._index_audio_cmu(*args, **kwargs)
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 797, in _index_audio_cmu
    str_timestamps_with_sil_conf))]
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 838, in _timestamp_extractor_cmu
    ) for x in str_timestamps])
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 838, in <listcomp>
    ) for x in str_timestamps])
ValueError: could not convert string to float: 'so'
```

**Comment by aalireza** [comment]
Can you provide the output of the command with the `--verbose` switch?

**Comment by jorenham** [comment]
```bash
$ sai --mode "cmu" --src_dir data/sample --search "security" --verbose
Found wave! Copying to data/sample/filtered/d050d861-08a4-47b0-b47a-23c6d49e030f_sample.wav
Converting d050d861-08a4-47b0-b47a-23c6d49e030f_sample.wav to a readable wav
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'data/sample/filtered/d050d861-08a4-47b0-b47a-23c6d49e030f_sample.wav':
  Metadata:
    encoder         : Lavf57.83.100
  Duration: 00:05:00.00, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'data/sample/staging/d050d861-08a4-47b0-b47a-23c6d49e030f_sample000.wav':
  Metadata:
    ISFT            : Lavf57.83.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc57.107.100 pcm_s16le
size=    9375kB time=00:05:00.00 bitrate= 256.0kbits/s speed=1.26e+03x    
video:0kB audio:9375kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000813%
data/sample/filtered/d050d861-08a4-47b0-b47a-23c6d49e030f_sample.wav was converted to data/sample/staging/d050d861-08a4-47b0-b47a-23c6d49e030f_sample000.wav Now removing the copy of d050d861-08a4-47b0-b47a-23c6d49e030f_sample.wav in filtered sub directory
Now indexing d050d861-08a4-47b0-b47a-23c6d49e030f_sample000.wav
Traceback (most recent call last):
  File "/project/venv/bin/sai", line 10, in <module>
    sys.exit(Main())
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__main__.py", line 101, in Main
    cli_script_wrapped(indexer)
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__main__.py", line 73, in cli_script_wrapped
    indexer.index_audio()
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 1110, in index_audio
    self._index_audio_cmu(*args, **kwargs)
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 797, in _index_audio_cmu
    str_timestamps_with_sil_conf))]
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 838, in _timestamp_extractor_cmu
    ) for x in str_timestamps])
  File "/project/venv/lib/python3.7/site-packages/SimpleAudioIndexer/__init__.py", line 838, in <listcomp>
    ) for x in str_timestamps])
ValueError: could not convert string to float: 'so'

```

**Comment by LiquidPrototype** [comment]
I get the same error but instead it's ValueError: could not convert string to float: right

**Comment by aalireza** [comment]
Pocketsphinx is having problems. In these cases it's a dead-end to try and make it work. (Yeah, Pocketsphinx by default has that bad of a performance!)
If you're lucky, by either playing with the audio or the models, you might get it working for a particular audio file.

I'll finally be updating the package soon, to use IBM's new APIs. If you won't mind uploading them to IBM then you'd be getting a much much better performance.

If you do mind uploading your files to IBM, there are Open source models out there since I last wrote this, like DeepSpeech but they don't provide timestamps (https://github.com/mozilla/DeepSpeech/issues/1806). One hacky way to get the timestamps which I haven't tried but might work, is windowing your audio - or just cut them in various lengths - and feed it to the their model and compare the output with the output of the file processed in full. It'll be ridiculous as you get more precise (Indexing a file of 10 seconds with 2 decimal points precision means processing 10*100/2 different files), but it might work! 
If you do this, let me know whether it worked or didn't.
