### ISSUE TITLE
Reinstalling Sai

### ISSUE THREAD

**Issue by deolu007** [aalireza/SimpleAudioIndexer#4]
I recently uninstalled and i'm trying to install it back but I'm getting these errors.

Exception:
Traceback (most recent call last):
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/adeoluwa/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/SimpleAudioIndexer'

**Comment by aalireza** [comment]
This is a problem with the configuration of your system: `pip install SimpleAudioIndexer` would try to install it in `/usr/local` and typically normal users don't have permission to do so. 

You have multiple options:

1. Change the permission: `sudo chown -R adeoluwa:adeoluwa /usr/local/lib/python2.7`. It should solve it, but that's the nuclear option and is not recommended.

2. You could install it via `sudo pip install SimpleAudioIndexer`. This should solve it since root has permission to modify `/usr/local`, but this way all users on your system would have access to `sai`, and although `sai` doesn't modify your system files, a random script might.

3. You could install it via `pip install --user SimpleAudioIndexer`. This should solve the permission issue since it would install it in your home directory.


Let me know if any of the above worked or you're still having a problem.

**Comment by deolu007** [comment]
Fixed! thanks

**Comment by aalireza** [comment]
Cool!
